// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pitchwire.Infrastructure.Persistence;

#nullable disable

namespace Pitchwire.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PitchwireDbContext))]
    partial class PitchwireDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pitchwire.Api.Domain.League", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("country");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_leagues");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_leagues_slug");

                    b.ToTable("leagues", (string)null);
                });

            modelBuilder.Entity("Pitchwire.Api.Domain.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AwayScore")
                        .HasColumnType("integer")
                        .HasColumnName("away_score");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("away_team_id");

                    b.Property<int>("HomeScore")
                        .HasColumnType("integer")
                        .HasColumnName("home_score");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("home_team_id");

                    b.Property<bool>("IsDegraded")
                        .HasColumnType("boolean")
                        .HasColumnName("is_degraded");

                    b.Property<DateTimeOffset>("KickoffUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("kickoff_utc");

                    b.Property<DateTimeOffset?>("LastEventAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_event_at");

                    b.Property<int>("LastEventSequence")
                        .HasColumnType("integer")
                        .HasColumnName("last_event_sequence");

                    b.Property<int>("Minute")
                        .HasColumnType("integer")
                        .HasColumnName("minute");

                    b.Property<int>("Round")
                        .HasColumnType("integer")
                        .HasColumnName("round");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_matches");

                    b.HasIndex("AwayTeamId")
                        .HasDatabaseName("ix_matches_away_team_id");

                    b.HasIndex("HomeTeamId")
                        .HasDatabaseName("ix_matches_home_team_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_matches_status");

                    b.HasIndex("KickoffUtc", "Id")
                        .HasDatabaseName("ix_matches_kickoff_utc_id");

                    b.HasIndex("SeasonId", "Round")
                        .HasDatabaseName("ix_matches_season_id_round");

                    b.HasIndex("Status", "LastEventAt")
                        .HasDatabaseName("ix_matches_status_last_event_at");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("Pitchwire.Api.Domain.MatchEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssistPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("assist_player_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("kind");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<int>("Minute")
                        .HasColumnType("integer")
                        .HasColumnName("minute");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_event_id");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_match_events");

                    b.HasIndex("MatchId", "Sequence")
                        .HasDatabaseName("ix_match_events_match_id_sequence");

                    b.HasIndex("Provider", "ProviderEventId")
                        .IsUnique()
                        .HasDatabaseName("ix_match_events_provider_event");

                    b.ToTable("match_events", (string)null);
                });

            modelBuilder.Entity("Pitchwire.Api.Domain.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_players");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_players_team_id");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("Pitchwire.Api.Domain.PlayerSeasonStats", b =>
                {
                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("Assists")
                        .HasColumnType("integer")
                        .HasColumnName("assists");

                    b.Property<int>("Goals")
                        .HasColumnType("integer")
                        .HasColumnName("goals");

                    b.Property<int>("RedCards")
                        .HasColumnType("integer")
                        .HasColumnName("red_cards");

                    b.Property<int>("YellowCards")
                        .HasColumnType("integer")
                        .HasColumnName("yellow_cards");

                    b.HasKey("SeasonId", "PlayerId")
                        .HasName("pk_player_season_stats");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_player_season_stats_player_id");

                    b.HasIndex("SeasonId", "Goals")
                        .HasDatabaseName("ix_player_season_stats_season_id_goals");

                    b.ToTable("player_season_stats", (string)null);
                });

            modelBuilder.Entity("Pitchwire.Api.Domain.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_seasons");

                    b.HasIndex("LeagueId", "Year")
                        .IsUnique()
                        .HasDatabaseName("ix_seasons_league_id_year");

                    b.ToTable("seasons", (string)null);
                });

            modelBuilder.Entity("Pitchwire.Api.Domain.Standing", b =>
                {
                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<int>("Drawn")
                        .HasColumnType("integer")
                        .HasColumnName("drawn");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("integer")
                        .HasColumnName("goals_against");

                    b.Property<int>("GoalsFor")
                        .HasColumnType("integer")
                        .HasColumnName("goals_for");

                    b.Property<int>("Lost")
                        .HasColumnType("integer")
                        .HasColumnName("lost");

                    b.Property<int>("Played")
                        .HasColumnType("integer")
                        .HasColumnName("played");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<int>("Won")
                        .HasColumnType("integer")
                        .HasColumnName("won");

                    b.HasKey("SeasonId", "TeamId")
                        .HasName("pk_standings");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_standings_team_id");

                    b.HasIndex("SeasonId", "Points", "GoalsFor")
                        .HasDatabaseName("ix_standings_season_id_points_goals_for");

                    b.ToTable("standings", (string)null);
                });

            modelBuilder.Entity("Pitchwire.Api.Domain.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("short_name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_teams_slug");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("Pitchwire.Api.Domain.TeamSeason", b =>
                {
                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("SeasonId", "TeamId")
                        .HasName("pk_team_seasons");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_team_seasons_team_id");

                    b.ToTable("team_seasons", (string)null);
                });

            modelBuilder.Entity("Pitchwire.Api.Domain.Match", b =>
                {
                    b.HasOne("Pitchwire.Api.Domain.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_matches_teams_away_team_id");

                    b.HasOne("Pitchwire.Api.Domain.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_matches_teams_home_team_id");

                    b.HasOne("Pitchwire.Api.Domain.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_matches_seasons_season_id");

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Pitchwire.Api.Domain.MatchEvent", b =>
                {
                    b.HasOne("Pitchwire.Api.Domain.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_events_matches_match_id");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Pitchwire.Api.Domain.Player", b =>
                {
                    b.HasOne("Pitchwire.Api.Domain.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_players_teams_team_id");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Pitchwire.Api.Domain.PlayerSeasonStats", b =>
                {
                    b.HasOne("Pitchwire.Api.Domain.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_season_stats_players_player_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Pitchwire.Api.Domain.Season", b =>
                {
                    b.HasOne("Pitchwire.Api.Domain.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seasons_leagues_league_id");

                    b.Navigation("League");
                });

            modelBuilder.Entity("Pitchwire.Api.Domain.Standing", b =>
                {
                    b.HasOne("Pitchwire.Api.Domain.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_standings_teams_team_id");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Pitchwire.Api.Domain.TeamSeason", b =>
                {
                    b.HasOne("Pitchwire.Api.Domain.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_seasons_seasons_season_id");

                    b.HasOne("Pitchwire.Api.Domain.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_seasons_teams_team_id");

                    b.Navigation("Season");

                    b.Navigation("Team");
                });
#pragma warning restore 612, 618
        }
    }
}
