/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/public-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PushPublicKey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["IssueDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CurrentDevice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["UpdatePreferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/me/favourites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["UpdateFavourites"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/me/push-subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Subscribe"];
        delete: operations["Unsubscribe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["IngestRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IngestResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Countries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/countries/{countrySlug}/leagues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Leagues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Seasons"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seasons/{seasonId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SeasonDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LiveMatches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{matchId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MatchDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{matchId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MatchTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seasons/{seasonId}/fixtures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Fixtures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seasons/{seasonId}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Results"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seasons/{seasonId}/table": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Table"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seasons/{seasonId}/scorers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Scorers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamId}/form": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Form"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CountrySummary: {
            /** Format: uuid */
            id: string;
            name: string;
            code: string;
            slug: string;
            /** Format: int32 */
            leagues: number;
        };
        DeviceSettings: {
            /** Format: uuid */
            id: string;
            timeZoneId: string;
            /** Format: time */
            quietHoursStart: null | string;
            /** Format: time */
            quietHoursEnd: null | string;
            notifyOnGoal: boolean;
            notifyOnRedCard: boolean;
            notifyOnKickoff: boolean;
            notifyOnFullTime: boolean;
            favourites: string[];
        };
        FavouritesRequest: {
            teamIds: string[];
        };
        FormEntry: {
            /** Format: uuid */
            matchId: string;
            /** Format: date-time */
            kickoffUtc: string;
            opponent: components["schemas"]["TeamRef"];
            atHome: boolean;
            /** Format: int32 */
            goalsFor: number;
            /** Format: int32 */
            goalsAgainst: number;
            outcome: string;
        };
        IngestRequest: {
            events: components["schemas"]["MatchEventPayload"][];
            lineups?: null | components["schemas"]["LineupPayload"][];
            statistics?: null | components["schemas"]["StatisticsPayload"][];
        };
        IngestResponse: {
            /** Format: int32 */
            accepted: number;
            /** Format: int32 */
            duplicate: number;
            /** Format: int32 */
            rejected: number;
            /**
             * Format: int32
             * @default 0
             */
            lineupsStored: number;
            /**
             * Format: int32
             * @default 0
             */
            statisticsStored: number;
        };
        LeagueRef: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            country: string;
        };
        LeagueSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            /** Format: int32 */
            tier: number;
            /** Format: uuid */
            countryId: string;
            country: string;
            /** Format: uuid */
            currentSeasonId: null | string;
        };
        LineupPayload: {
            /** Format: uuid */
            matchId: string;
            /** Format: uuid */
            teamId: string;
            formation: string;
            players: components["schemas"]["LineupPlayerPayload"][];
        };
        LineupPlayerPayload: {
            /** Format: uuid */
            playerId: string;
            /** Format: int32 */
            shirtNumber: number;
            position: components["schemas"]["LineupPosition"];
            starter: boolean;
        };
        LineupPlayerView: {
            /** Format: uuid */
            playerId: string;
            player: string;
            /** Format: int32 */
            shirtNumber: number;
            position: string;
            starter: boolean;
            /** Format: int32 */
            minutesPlayed: number;
            /** Format: int32 */
            goals: number;
            /** Format: int32 */
            assists: number;
            /** Format: int32 */
            yellowCards: number;
            /** Format: int32 */
            redCards: number;
            /** Format: double */
            rating: null | number;
        };
        LineupPosition: number;
        MatchDetail: {
            match: components["schemas"]["MatchSummary"];
            timeline: components["schemas"]["MatchEventView"][];
            lineups: components["schemas"]["TeamSheetView"][];
            statistics: components["schemas"]["TeamStatisticsView"][];
        };
        MatchEventKind: number;
        MatchEventPayload: {
            providerEventId: string;
            /** Format: uuid */
            matchId: string;
            /** Format: int32 */
            sequence: number;
            /** Format: int32 */
            minute: number;
            kind: components["schemas"]["MatchEventKind"];
            /** Format: uuid */
            teamId: string;
            /** Format: uuid */
            playerId: null | string;
            /** Format: uuid */
            assistPlayerId: null | string;
            /** Format: date-time */
            occurredAt: string;
            /** Format: uuid */
            replacedPlayerId?: null | string;
        };
        MatchEventView: {
            /** Format: int32 */
            sequence: number;
            /** Format: int32 */
            minute: number;
            kind: string;
            /** Format: uuid */
            teamId: string;
            player: null | string;
            assist: null | string;
            replaced: null | string;
        };
        MatchSummary: {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            round: number;
            /** Format: date-time */
            kickoffUtc: string;
            status: string;
            /** Format: int32 */
            minute: number;
            /** Format: int32 */
            homeScore: number;
            /** Format: int32 */
            awayScore: number;
            isDegraded: boolean;
            league: components["schemas"]["LeagueRef"];
            home: components["schemas"]["TeamRef"];
            away: components["schemas"]["TeamRef"];
        };
        PageOfMatchSummary: {
            value: components["schemas"]["MatchSummary"][];
            nextLink: null | string;
        };
        PreferencesRequest: {
            timeZoneId: string;
            /** Format: time */
            quietHoursStart: null | string;
            /** Format: time */
            quietHoursEnd: null | string;
            notifyOnGoal: boolean;
            notifyOnRedCard: boolean;
            notifyOnKickoff: boolean;
            notifyOnFullTime: boolean;
        };
        PushKey: {
            publicKey: string;
        };
        ScorerRow: {
            /** Format: uuid */
            playerId: string;
            player: string;
            team: components["schemas"]["TeamRef"];
            /** Format: int32 */
            goals: number;
            /** Format: int32 */
            assists: number;
        };
        SeasonDetail: {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            year: number;
            league: components["schemas"]["LeagueRef"];
            teams: components["schemas"]["TeamRef"][];
            rounds: number[];
        };
        SeasonSummary: {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            year: number;
            /** Format: uuid */
            leagueId: string;
            league: string;
            leagueSlug: string;
        };
        StatisticsPayload: {
            /** Format: uuid */
            matchId: string;
            /** Format: uuid */
            teamId: string;
            /** Format: int32 */
            asOfMinute: number;
            /** Format: int32 */
            possession: number;
            /** Format: int32 */
            shots: number;
            /** Format: int32 */
            shotsOnTarget: number;
            /** Format: int32 */
            corners: number;
            /** Format: int32 */
            fouls: number;
            /** Format: int32 */
            offsides: number;
        };
        SubscriptionKeys: {
            p256dh: string;
            auth: string;
        };
        SubscriptionRequest: {
            endpoint: string;
            keys: components["schemas"]["SubscriptionKeys"];
        };
        TableRow: {
            /** Format: int32 */
            position: number;
            team: components["schemas"]["TeamRef"];
            /** Format: int32 */
            played: number;
            /** Format: int32 */
            won: number;
            /** Format: int32 */
            drawn: number;
            /** Format: int32 */
            lost: number;
            /** Format: int32 */
            goalsFor: number;
            /** Format: int32 */
            goalsAgainst: number;
            /** Format: int32 */
            goalDifference: number;
            /** Format: int32 */
            points: number;
        };
        TeamRef: {
            /** Format: uuid */
            id: string;
            name: string;
            shortName: string;
            slug: string;
        };
        TeamSheetView: {
            /** Format: uuid */
            teamId: string;
            formation: string;
            players: components["schemas"]["LineupPlayerView"][];
        };
        TeamStatisticsView: {
            /** Format: uuid */
            teamId: string;
            /** Format: int32 */
            asOfMinute: number;
            /** Format: int32 */
            possession: number;
            /** Format: int32 */
            shots: number;
            /** Format: int32 */
            shotsOnTarget: number;
            /** Format: int32 */
            corners: number;
            /** Format: int32 */
            fouls: number;
            /** Format: int32 */
            offsides: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    PushPublicKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushKey"];
                };
            };
        };
    };
    IssueDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceSettings"];
                };
            };
        };
    };
    CurrentDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceSettings"];
                };
            };
        };
    };
    UpdatePreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceSettings"];
                };
            };
        };
    };
    UpdateFavourites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FavouritesRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceSettings"];
                };
            };
        };
    };
    Subscribe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Unsubscribe: {
        parameters: {
            query: {
                endpoint: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Countries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountrySummary"][];
                };
            };
        };
    };
    Leagues: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                countrySlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeagueSummary"][];
                };
            };
        };
    };
    Seasons: {
        parameters: {
            query?: {
                leagueId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonSummary"][];
                };
            };
        };
    };
    SeasonDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seasonId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LiveMatches: {
        parameters: {
            query?: {
                $top?: number;
                $skiptoken?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOfMatchSummary"];
                };
            };
        };
    };
    MatchDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matchId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MatchTimeline: {
        parameters: {
            query?: {
                from?: number;
            };
            header?: never;
            path: {
                matchId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchEventView"][];
                };
            };
        };
    };
    Fixtures: {
        parameters: {
            query?: {
                round?: number;
                teamId?: string;
                $top?: number;
                $skiptoken?: string;
            };
            header?: never;
            path: {
                seasonId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOfMatchSummary"];
                };
            };
        };
    };
    Results: {
        parameters: {
            query?: {
                round?: number;
                teamId?: string;
                $top?: number;
                $skiptoken?: string;
            };
            header?: never;
            path: {
                seasonId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOfMatchSummary"];
                };
            };
        };
    };
    Table: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seasonId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableRow"][];
                };
            };
        };
    };
    Scorers: {
        parameters: {
            query?: {
                $top?: number;
            };
            header?: never;
            path: {
                seasonId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScorerRow"][];
                };
            };
        };
    };
    Form: {
        parameters: {
            query: {
                seasonId: string;
                count?: number;
            };
            header?: never;
            path: {
                teamId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormEntry"][];
                };
            };
        };
    };
}
